# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c4c9184ef59a6343de92d919c2790e2e32e8da2e883c033525375b091b37d8d0c7c5bf5bf6dc0501bcf6b1ddcadd764c990316166503ea474249a4bb441dbff

test:
  secret_key_base: 4841328f97571b1a8f3d668988781a81141d8aed99670de8b3f1c31598268733f77cc4ee71de00745e6468f5ebdbc7205ab6dcc0a10e6888c308871a442f6840

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
